project:
  type: book
  output-dir: docs

book:
  title: "bayesian-statistics-the-fun-way"
  author: "Norah Jones"
  date: "4/23/2023"
  chapters:
      - index.qmd
      - intro.qmd
      - summary.qmd
      - references.qmd
      - part: part_1.qmd
        chapters:
          - index.qmd
          - intro.qmd
  


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

