# Creating a Binomial Probability Distribution

## Questions

### What are the parameters of the binomial distribution for the probability of rolling either a 1 or a 20 on a 20-sided die, if we roll the die 12 times?

$n = 12$

$k = 1$

$p = \frac{2}{20} = 10\%$

### There are four aces in a deck of 52 cards. If you pull a card, return the card, then reshuffle and pull a card again, how many ways can you pull just one ace in five pulls?

```{python}

from sympy import binomial

binomial(5,1)
```

### For the example in question 2, what is the probability of pulling five aces in 10 pulls (remember the card is shuffled back in the deck when it is pulled)?

```{python}
from sympy import binomial

def binomial_probability(n, k, p):
    q = 1 - p  # probability of failure
    pmf = binomial(n, k) * p**k * q**(n-k)  # binomial distribution PMF
    return pmf

n = 10 # number of trials
k = 5   # number of successes
p = 1/13 # probability of success

probability = binomial_probability(n, k, p)
print(probability)
print(1/32000 - probability)
```

### When you're searching for a new job, it's always helpful to have more than one offer on the table so you can use it in negotiations. If you have a 1/5 probability of receiving a job offer when you interview, and you interview with seven companies in a month, what is the probability you'll have at least two competing offers by the end of that month?

### You get a bunch of recruiter emails and find out you have 25 interviews lined up in the next month. Unfortunately, you know this will leave you exhausted, and the probability of getting an offer will drop to 1/10 if you're tired. You really don't want to go on this many interviews unless you are at least twice as likely to get at least two competing offers. Are you more likely to get at least two offers if you go for 25 interviews, or stick to just 7?
